import { defaultTheme } from "../../themes/default/index.js";
import { resolveDefaultThemeMode } from "../../theme-mode.js";
import type { BreadcrumbItemData } from "../../themes/types.js";
import type { PageData, SidebarItem, TocItem } from "../../types.js";
import type { ParentComponent } from "solid-js";

// @ts-ignore: generated by the docs plugin from the configured theme path.
import { theme as configuredTheme } from "virtual:folio-theme";

interface DocsLayoutShellProps {
  config: any;
  tree: SidebarItem[];
  pages: PageData[];
  currentPage: PageData | undefined;
  onNavigate: (url: string) => void;
  breadcrumbs: BreadcrumbItemData[];
  toc: TocItem[];
  prev: { title: string; href: string } | undefined;
  next: { title: string; href: string } | undefined;
  sourceContent?: string;
}

export const DocsLayoutShell: ParentComponent<DocsLayoutShellProps> = (props) => {
  const ThemeProvider = configuredTheme.Provider || defaultTheme.Provider;
  if (!ThemeProvider) throw new Error("Folio theme must provide a ThemeProvider");
  return (
    <ThemeProvider defaultTheme={resolveDefaultThemeMode(props.config)} storageKey="nikala-theme">
      <configuredTheme.Layout config={props.config} tree={props.tree} pages={props.pages} currentPage={props.currentPage} onNavigate={props.onNavigate} breadcrumbs={props.breadcrumbs} toc={props.toc} prev={props.prev} next={props.next} sourceContent={props.sourceContent}>
        {props.children}
      </configuredTheme.Layout>
    </ThemeProvider>
  );
};
